### ISSUE TITLE
Add introduction 

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/basic-build-scans#2]
@kousen One thing I missed when reviewing the guide is that it lacks some introduction about what a build scan is.

We can take the sentence from https://gradle.com/scans/get-started:

> A build scan is a shareable and centralized record of a build that provides insights into what happened and why. By applying the build scan plugin to your project, you can create a build scan in the Gradle Cloud for free.

**Comment by kousen** [comment]
I added that sentence to an Introduction section and pushed to the repo. Now needs a (very quick) review and to be published, which @ysb33r knows how to do

**Comment by pioterj** [comment]
Can it be closed?

**Comment by kousen** [comment]
Yes, we're all set.

Ken

**Comment by ysb33r** [comment]
Seen as 3565288f67fc7d0d7706057f153ff5461c05fbc5.
